local ReplicatedStorage=game:GetService("ReplicatedStorage")
print("RunMatchService: boot")
local StateContract=require(ReplicatedStorage:WaitForChild("State"):WaitForChild("StateContract"))
StateContract.Ensure()
print("RunMatchService: state ensured")
local serverFolder=script.Parent
local servicesFolder=serverFolder:WaitForChild("Services")
local PlayerStateService=require(servicesFolder:WaitForChild("PlayerStateService"))
PlayerStateService.Start()
print("RunMatchService: PlayerState started")
local QualificationService=require(servicesFolder:WaitForChild("QualificationService"))
QualificationService.Start()
print("RunMatchService: QualificationService started")
local ExitDoorService=require(servicesFolder:WaitForChild("ExitDoorService"))
local door=workspace:FindFirstChild("ExitDoor")
if door then
	ExitDoorService.BindDoor(door)
	print("RunMatchService: ExitDoor bound")
else
	warn("RunMatchService: ExitDoor not found in Workspace")
end
local RoundOrchestrator=require(servicesFolder:WaitForChild("RoundOrchestrator"))
RoundOrchestrator.Start()
print("RunMatchService: RoundOrchestrator started")
local MatchService=require(servicesFolder:WaitForChild("MatchService"))
print("RunMatchService: starting match loop")
task.spawn(function()
	MatchService.RunLoop()
end)
