local ReplicatedStorage = game:GetService("ReplicatedStorage")
local ServerScriptService = game:GetService("ServerScriptService")
print("Server Start: boot")
local ServerRoot = ServerScriptService:WaitForChild("Server")
local Services = ServerRoot:WaitForChild("Services")
local StateContract = require(script.Parent:WaitForChild("StateContract"))
StateContract.Ensure()
local PlayerStateService = require(Services:WaitForChild("PlayerStateService"))
PlayerStateService.Start()
local RoundOrchestrator = require(Services:WaitForChild("RoundOrchestrator"))
RoundOrchestrator.Start()
local MatchService = require(Services:WaitForChild("MatchService"))
MatchService.RunLoop()
