local Constants = {
	GUI_NAME = "HomepageOverlay",
	CHARACTER_POSITION = Vector3.new(-150, 58, 218),
	CAMERA_POSITION = Vector3.new(-145, 61, 210),
	CAMERA_FOCUS_HEIGHT = 1.35,
	CAMERA_FOV = 60,
	CAMERA_RIGHT_YAW_DEGREES = 30,
	PLAYER_RIGHT_YAW_DEGREES = -30,
	CAMERA_SWAY_YAW_DEGREES = 1.2,
	CAMERA_SWAY_PITCH_DEGREES = 0.3,
	CAMERA_SWAY_YAW_HZ = 0.045,
	CAMERA_SWAY_PITCH_HZ = 0.031,
	CAMERA_FOV_BREATHE_DELTA = 0.7,
	CAMERA_FOV_BREATHE_HZ = 0.035,
	CAMERA_MOTION_BLEND_SPEED = 4.0,
	CAMERA_FOCUS_DISTANCE = 64,
	LOBBY_PLAYER_TARGET = 6,
}

return Constants
